name: GitHub Pages deploy
on:
  push:
    branches:
      - gh-pages
jobs:
  checkout-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@master
        env:
          EMAIL: 1253478653@qq.com              # must be a verified email
          GH_TOKEN: ${{ secrets.access_token }} # https://github.com/settings/tokens
          BUILD_DIR: doc                        # "_site/" by default
          CNAME: https://xuzpeng.github.io/fiora-ui-react # in case of custom domain
          JEKYLL_SITE: "YES"                    # only in case of a Jekyll site
