name: NPM Publish

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: test
        run: |
          yarn install
          yarn test
        env:
          CI: true

  publish-npm:
    needs: prebuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: https://registry.npmjs.org/
      - name: build components
        run: |
          yarn install
          yarn run build:components
      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version
      # 关于创建 release 的更多参数，可以查看 actions/create-release@v1
      - name: Create Release for Tag
        id: release_tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 这块需要用到 github的token，因为需要对分之进行代码推送
        with:
          tag_name: v${{ steps.package-version.outputs.version }}
          release_name: v${{ steps.package-version.outputs.version }}
          prerelease: false # 是否为预发布版本
      - name: publish package
        run: |
          cp package.json README.md ./dist
          cd dist
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

